"""
Ingestion — Contextual Chunking & Structural Metadata (Skill 4).

Each chunk gets a contextual prefix generated by the small LLM (Anthropic-style
contextual retrieval). The prefix situates the chunk in its document so it is
retrievable by lay-language queries that never use statutory wording.

The prefix is prepended BEFORE embedding — so the stored, embedded text is:
    {contextual_prefix}\n\n{chunk_text}

This is a one-time offline cost. Anthropic reports this cuts retrieval failures ~35%;
stacked with contextual BM25 + reranker, the combined lift is ~67%.
"""
import logging
import uuid
from app.pipeline import embeddings, vector_store, bm25_index, llm_client

logger = logging.getLogger(__name__)

_PREFIX_PROMPT = """You are indexing a Bangladeshi legal document for retrieval.
Document: {document_title}
Hierarchy: {hierarchy}
Effective: {effective_date}; Amendment status: {amendment_status}

Write 2-3 sentences that explain, in plain terms, what this chunk is about,
where it sits in the document, and what real-world situations it applies to.
Do not add information not present in the chunk. Output only the context sentences.

Chunk:
{chunk_text}"""


async def generate_contextual_prefix(
    chunk_text: str,
    document_title: str,
    hierarchy: str,
    effective_date: str = "unknown",
    amendment_status: str = "current",
) -> str:
    """Generate the Anthropic-style contextual prefix for a single chunk."""
    prompt = _PREFIX_PROMPT.format(
        document_title=document_title,
        hierarchy=hierarchy,
        effective_date=effective_date,
        amendment_status=amendment_status,
        chunk_text=chunk_text[:800],
    )
    prefix = await llm_client.generate(prompt, model=llm_client.SMALL_MODEL)
    return prefix.strip()


async def ingest_document(
    chunks: list[dict],
    namespace: str = "national",
    generate_prefixes: bool = True,
) -> int:
    """
    Ingest a batch of document chunks into ChromaDB (dense) + BM25 (sparse).

    Each chunk dict must have:
      chunk_id      — unique identifier
      text          — the chunk body
      metadata      — dict matching ChunkMetadata fields
    Optionally:
      document_title, hierarchy, effective_date, amendment_status
      (used for contextual prefix generation)
    """
    if not chunks:
        return 0

    processed: list[dict] = []
    for chunk in chunks:
        raw_text = chunk["text"]
        chunk_id = chunk.get("chunk_id") or str(uuid.uuid4())

        # Generate contextual prefix (one-time cost; skip in fast-reload mode)
        if generate_prefixes:
            prefix = await generate_contextual_prefix(
                chunk_text=raw_text,
                document_title=chunk.get("document_title", ""),
                hierarchy=chunk.get("hierarchy", ""),
                effective_date=chunk.get("effective_date", ""),
                amendment_status=chunk.get("amendment_status", "current"),
            )
            indexed_text = f"{prefix}\n\n{raw_text}" if prefix else raw_text
        else:
            indexed_text = raw_text

        processed.append({
            "chunk_id": chunk_id,
            "text": indexed_text,
            "metadata": chunk.get("metadata", {}),
        })

    # Dense embed + upsert to ChromaDB
    texts = [c["text"] for c in processed]
    vecs = embeddings.embed(texts)
    if vecs:
        chunks_with_embed = [{**c, "embedding": v} for c, v in zip(processed, vecs)]
        vector_store.upsert_chunks(chunks_with_embed, namespace=namespace)
    else:
        logger.warning("Embedder unavailable — dense index not populated for namespace '%s'", namespace)

    # Build BM25 index for this namespace
    # In production you'd load ALL existing chunks first; here we build from this batch.
    bm25_index.build_index(processed, namespace=namespace)

    logger.info("Ingested %d chunks → namespace='%s'", len(processed), namespace)
    return len(processed)
