"""alert_system

Revision ID: 1e240152fca9
Revises: 035cab04b834
Create Date: 2026-06-01 11:59:57.594062
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '1e240152fca9'
down_revision: Union[str, None] = '035cab04b834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone_type', sa.Enum('rape', 'murder', 'alert', 'university', name='zonetype'), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Integer(), nullable=False),
    sa.Column('description_public', sa.Text(), nullable=True),
    sa.Column('related_alert_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='zonestatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_related_alert_id'), 'zones', ['related_alert_id'], unique=False)
    op.create_index(op.f('ix_zones_tenant_id'), 'zones', ['tenant_id'], unique=False)
    op.create_table('alert_bans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('device_fingerprint_hash', sa.String(length=64), nullable=True),
    sa.Column('ban_reason', sa.Text(), nullable=False),
    sa.Column('banned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_bans_device_fingerprint_hash'), 'alert_bans', ['device_fingerprint_hash'], unique=False)
    op.create_index(op.f('ix_alert_bans_user_id'), 'alert_bans', ['user_id'], unique=False)
    op.create_table('alert_phase1_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('encrypted_payload', sa.LargeBinary(), nullable=True),
    sa.Column('emergency_contacts', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_phase1_records_user_id'), 'alert_phase1_records', ['user_id'], unique=True)
    op.create_table('user_fcm_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('fcm_token', sa.String(length=512), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.Enum('android', 'ios', 'web', name='fcmplatform'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_fcm_tokens_user_id'), 'user_fcm_tokens', ['user_id'], unique=False)
    op.create_table('user_location_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_id_hash', sa.String(length=64), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('geofence_consent', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_location_snapshots_last_seen_at'), 'user_location_snapshots', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_user_location_snapshots_user_id'), 'user_location_snapshots', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_location_snapshots_user_id_hash'), 'user_location_snapshots', ['user_id_hash'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('anonymous_actor_hash', sa.String(length=64), nullable=False),
    sa.Column('encrypted_actor_link', sa.LargeBinary(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('gps_accuracy_m', sa.Integer(), nullable=True),
    sa.Column('gps_status', sa.Enum('ok', 'stale', 'unavailable', name='gpsstatus'), nullable=False),
    sa.Column('device_fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('active', 'user_safe', 'closed', 'false_alert', 'resolved', name='alertstate'), nullable=False),
    sa.Column('phase1_record_id', sa.Uuid(), nullable=True),
    sa.Column('alert_zone_id', sa.Uuid(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['phase1_record_id'], ['alert_phase1_records.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_anonymous_actor_hash'), 'alert_events', ['anonymous_actor_hash'], unique=False)
    op.create_index(op.f('ix_alert_events_created_at'), 'alert_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_events_device_fingerprint_hash'), 'alert_events', ['device_fingerprint_hash'], unique=False)
    op.create_index(op.f('ix_alert_events_event_id'), 'alert_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_alert_events_state'), 'alert_events', ['state'], unique=False)
    op.create_index(op.f('ix_alert_events_tenant_id'), 'alert_events', ['tenant_id'], unique=False)
    op.create_table('alert_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('encrypted_blob_ref', sa.String(length=500), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('capture_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('media_type', sa.Enum('photo', 'video', 'audio', 'document', name='mediatype'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['alert_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_evidence_event_id'), 'alert_evidence', ['event_id'], unique=False)
    op.create_table('alert_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_type', sa.Enum('proctor', 'nearby_user', 'contact_sms', 'contact_email', name='recipienttype'), nullable=False),
    sa.Column('recipient_ref', sa.String(length=512), nullable=False),
    sa.Column('channel', sa.Enum('push', 'sms', 'email', name='notifchannel'), nullable=False),
    sa.Column('fcm_message_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'failed', 'suppressed', name='notifstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['alert_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_notifications_event_id'), 'alert_notifications', ['event_id'], unique=False)
    op.create_table('alert_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('responder_user_hash', sa.String(length=64), nullable=False),
    sa.Column('response_type', sa.Enum('responding', 'cannot_help', 'flagged_fake', name='responsetype'), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['alert_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_responses_event_id'), 'alert_responses', ['event_id'], unique=False)
    # Composite performance indexes
    op.create_index('ix_alert_events_state_created', 'alert_events', ['state', 'created_at'])
    op.create_index('ix_alert_events_tenant_state', 'alert_events', ['tenant_id', 'state'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_events_tenant_state', table_name='alert_events')
    op.drop_index('ix_alert_events_state_created', table_name='alert_events')
    op.drop_index(op.f('ix_alert_responses_event_id'), table_name='alert_responses')
    op.drop_table('alert_responses')
    op.drop_index(op.f('ix_alert_notifications_event_id'), table_name='alert_notifications')
    op.drop_table('alert_notifications')
    op.drop_index(op.f('ix_alert_evidence_event_id'), table_name='alert_evidence')
    op.drop_table('alert_evidence')
    op.drop_index(op.f('ix_alert_events_tenant_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_state'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_event_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_device_fingerprint_hash'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_created_at'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_anonymous_actor_hash'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_user_location_snapshots_user_id_hash'), table_name='user_location_snapshots')
    op.drop_index(op.f('ix_user_location_snapshots_user_id'), table_name='user_location_snapshots')
    op.drop_index(op.f('ix_user_location_snapshots_last_seen_at'), table_name='user_location_snapshots')
    op.drop_table('user_location_snapshots')
    op.drop_index(op.f('ix_user_fcm_tokens_user_id'), table_name='user_fcm_tokens')
    op.drop_table('user_fcm_tokens')
    op.drop_index(op.f('ix_alert_phase1_records_user_id'), table_name='alert_phase1_records')
    op.drop_table('alert_phase1_records')
    op.drop_index(op.f('ix_alert_bans_user_id'), table_name='alert_bans')
    op.drop_index(op.f('ix_alert_bans_device_fingerprint_hash'), table_name='alert_bans')
    op.drop_table('alert_bans')
    op.drop_index(op.f('ix_zones_tenant_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_related_alert_id'), table_name='zones')
    op.drop_table('zones')
    # ### end Alembic commands ###
